// Generated by the protocol buffer compiler.  DO NOT EDIT!

package com.browseengine.bobo.protobuf;

public final class BrowseRequestBPO {
  private BrowseRequestBPO() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class Property extends
      com.google.protobuf.GeneratedMessage {
    // Use Property.newBuilder() to construct.
    private Property() {}
    
    private static final Property defaultInstance = new Property();
    public static Property getDefaultInstance() {
      return defaultInstance;
    }
    
    public Property getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.browseengine.bobo.protobuf.BrowseRequestBPO.internal_static_com_browseengine_bobo_protobuf_Property_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.browseengine.bobo.protobuf.BrowseRequestBPO.internal_static_com_browseengine_bobo_protobuf_Property_fieldAccessorTable;
    }
    
    // required string key = 1;
    public static final int KEY_FIELD_NUMBER = 1;
    private boolean hasKey;
    private java.lang.String key_ = "";
    public boolean hasKey() { return hasKey; }
    public java.lang.String getKey() { return key_; }
    
    // optional string val = 2;
    public static final int VAL_FIELD_NUMBER = 2;
    private boolean hasVal;
    private java.lang.String val_ = "";
    public boolean hasVal() { return hasVal; }
    public java.lang.String getVal() { return val_; }
    
    public final boolean isInitialized() {
      if (!hasKey) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (hasKey()) {
        output.writeString(1, getKey());
      }
      if (hasVal()) {
        output.writeString(2, getVal());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasKey()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getKey());
      }
      if (hasVal()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getVal());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.browseengine.bobo.protobuf.BrowseRequestBPO.Property parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.browseengine.bobo.protobuf.BrowseRequestBPO.Property parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.browseengine.bobo.protobuf.BrowseRequestBPO.Property parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.browseengine.bobo.protobuf.BrowseRequestBPO.Property parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.browseengine.bobo.protobuf.BrowseRequestBPO.Property parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.browseengine.bobo.protobuf.BrowseRequestBPO.Property parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.browseengine.bobo.protobuf.BrowseRequestBPO.Property parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input).buildParsed();
    }
    public static com.browseengine.bobo.protobuf.BrowseRequestBPO.Property parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.browseengine.bobo.protobuf.BrowseRequestBPO.Property parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.browseengine.bobo.protobuf.BrowseRequestBPO.Property parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.browseengine.bobo.protobuf.BrowseRequestBPO.Property prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.browseengine.bobo.protobuf.BrowseRequestBPO.Property result;
      
      // Construct using com.browseengine.bobo.protobuf.BrowseRequestBPO.Property.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.browseengine.bobo.protobuf.BrowseRequestBPO.Property();
        return builder;
      }
      
      protected com.browseengine.bobo.protobuf.BrowseRequestBPO.Property internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.browseengine.bobo.protobuf.BrowseRequestBPO.Property();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.browseengine.bobo.protobuf.BrowseRequestBPO.Property.getDescriptor();
      }
      
      public com.browseengine.bobo.protobuf.BrowseRequestBPO.Property getDefaultInstanceForType() {
        return com.browseengine.bobo.protobuf.BrowseRequestBPO.Property.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.browseengine.bobo.protobuf.BrowseRequestBPO.Property build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.browseengine.bobo.protobuf.BrowseRequestBPO.Property buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.browseengine.bobo.protobuf.BrowseRequestBPO.Property buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.browseengine.bobo.protobuf.BrowseRequestBPO.Property returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.browseengine.bobo.protobuf.BrowseRequestBPO.Property) {
          return mergeFrom((com.browseengine.bobo.protobuf.BrowseRequestBPO.Property)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.browseengine.bobo.protobuf.BrowseRequestBPO.Property other) {
        if (other == com.browseengine.bobo.protobuf.BrowseRequestBPO.Property.getDefaultInstance()) return this;
        if (other.hasKey()) {
          setKey(other.getKey());
        }
        if (other.hasVal()) {
          setVal(other.getVal());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              setKey(input.readString());
              break;
            }
            case 18: {
              setVal(input.readString());
              break;
            }
          }
        }
      }
      
      
      // required string key = 1;
      public boolean hasKey() {
        return result.hasKey();
      }
      public java.lang.String getKey() {
        return result.getKey();
      }
      public Builder setKey(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasKey = true;
        result.key_ = value;
        return this;
      }
      public Builder clearKey() {
        result.hasKey = false;
        result.key_ = getDefaultInstance().getKey();
        return this;
      }
      
      // optional string val = 2;
      public boolean hasVal() {
        return result.hasVal();
      }
      public java.lang.String getVal() {
        return result.getVal();
      }
      public Builder setVal(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasVal = true;
        result.val_ = value;
        return this;
      }
      public Builder clearVal() {
        result.hasVal = false;
        result.val_ = getDefaultInstance().getVal();
        return this;
      }
    }
    
    static {
      com.browseengine.bobo.protobuf.BrowseRequestBPO.getDescriptor();
    }
    
    static {
      com.browseengine.bobo.protobuf.BrowseRequestBPO.internalForceInit();
    }
  }
  
  public static final class Selection extends
      com.google.protobuf.GeneratedMessage {
    // Use Selection.newBuilder() to construct.
    private Selection() {}
    
    private static final Selection defaultInstance = new Selection();
    public static Selection getDefaultInstance() {
      return defaultInstance;
    }
    
    public Selection getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.browseengine.bobo.protobuf.BrowseRequestBPO.internal_static_com_browseengine_bobo_protobuf_Selection_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.browseengine.bobo.protobuf.BrowseRequestBPO.internal_static_com_browseengine_bobo_protobuf_Selection_fieldAccessorTable;
    }
    
    public enum Operation
        implements com.google.protobuf.ProtocolMessageEnum {
      OR(0, 0),
      AND(1, 1),
      ;
      
      
      public final int getNumber() { return value; }
      
      public static Operation valueOf(int value) {
        switch (value) {
          case 0: return OR;
          case 1: return AND;
          default: return null;
        }
      }
      
      public static com.google.protobuf.Internal.EnumLiteMap<Operation>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<Operation>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Operation>() {
              public Operation findValueByNumber(int number) {
                return Operation.valueOf(number)
      ;        }
            };
      
      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.browseengine.bobo.protobuf.BrowseRequestBPO.Selection.getDescriptor().getEnumTypes().get(0);
      }
      
      private static final Operation[] VALUES = {
        OR, AND, 
      };
      public static Operation valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }
      private final int index;
      private final int value;
      private Operation(int index, int value) {
        this.index = index;
        this.value = value;
      }
      
      static {
        com.browseengine.bobo.protobuf.BrowseRequestBPO.getDescriptor();
      }
    }
    
    // required string name = 1;
    public static final int NAME_FIELD_NUMBER = 1;
    private boolean hasName;
    private java.lang.String name_ = "";
    public boolean hasName() { return hasName; }
    public java.lang.String getName() { return name_; }
    
    // repeated string values = 2;
    public static final int VALUES_FIELD_NUMBER = 2;
    private java.util.List<java.lang.String> values_ =
      java.util.Collections.emptyList();
    public java.util.List<java.lang.String> getValuesList() {
      return values_;
    }
    public int getValuesCount() { return values_.size(); }
    public java.lang.String getValues(int index) {
      return values_.get(index);
    }
    
    // repeated string notValues = 3;
    public static final int NOTVALUES_FIELD_NUMBER = 3;
    private java.util.List<java.lang.String> notValues_ =
      java.util.Collections.emptyList();
    public java.util.List<java.lang.String> getNotValuesList() {
      return notValues_;
    }
    public int getNotValuesCount() { return notValues_.size(); }
    public java.lang.String getNotValues(int index) {
      return notValues_.get(index);
    }
    
    // optional .com.browseengine.bobo.protobuf.Selection.Operation op = 4 [default = OR];
    public static final int OP_FIELD_NUMBER = 4;
    private boolean hasOp;
    private com.browseengine.bobo.protobuf.BrowseRequestBPO.Selection.Operation op_ = com.browseengine.bobo.protobuf.BrowseRequestBPO.Selection.Operation.OR;
    public boolean hasOp() { return hasOp; }
    public com.browseengine.bobo.protobuf.BrowseRequestBPO.Selection.Operation getOp() { return op_; }
    
    // repeated .com.browseengine.bobo.protobuf.Property props = 5;
    public static final int PROPS_FIELD_NUMBER = 5;
    private java.util.List<com.browseengine.bobo.protobuf.BrowseRequestBPO.Property> props_ =
      java.util.Collections.emptyList();
    public java.util.List<com.browseengine.bobo.protobuf.BrowseRequestBPO.Property> getPropsList() {
      return props_;
    }
    public int getPropsCount() { return props_.size(); }
    public com.browseengine.bobo.protobuf.BrowseRequestBPO.Property getProps(int index) {
      return props_.get(index);
    }
    
    public final boolean isInitialized() {
      if (!hasName) return false;
      for (com.browseengine.bobo.protobuf.BrowseRequestBPO.Property element : getPropsList()) {
        if (!element.isInitialized()) return false;
      }
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (hasName()) {
        output.writeString(1, getName());
      }
      for (java.lang.String element : getValuesList()) {
        output.writeString(2, element);
      }
      for (java.lang.String element : getNotValuesList()) {
        output.writeString(3, element);
      }
      if (hasOp()) {
        output.writeEnum(4, getOp().getNumber());
      }
      for (com.browseengine.bobo.protobuf.BrowseRequestBPO.Property element : getPropsList()) {
        output.writeMessage(5, element);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasName()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getName());
      }
      {
        int dataSize = 0;
        for (java.lang.String element : getValuesList()) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeStringSizeNoTag(element);
        }
        size += dataSize;
        size += 1 * getValuesList().size();
      }
      {
        int dataSize = 0;
        for (java.lang.String element : getNotValuesList()) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeStringSizeNoTag(element);
        }
        size += dataSize;
        size += 1 * getNotValuesList().size();
      }
      if (hasOp()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(4, getOp().getNumber());
      }
      for (com.browseengine.bobo.protobuf.BrowseRequestBPO.Property element : getPropsList()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, element);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.browseengine.bobo.protobuf.BrowseRequestBPO.Selection parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.browseengine.bobo.protobuf.BrowseRequestBPO.Selection parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.browseengine.bobo.protobuf.BrowseRequestBPO.Selection parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.browseengine.bobo.protobuf.BrowseRequestBPO.Selection parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.browseengine.bobo.protobuf.BrowseRequestBPO.Selection parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.browseengine.bobo.protobuf.BrowseRequestBPO.Selection parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.browseengine.bobo.protobuf.BrowseRequestBPO.Selection parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input).buildParsed();
    }
    public static com.browseengine.bobo.protobuf.BrowseRequestBPO.Selection parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.browseengine.bobo.protobuf.BrowseRequestBPO.Selection parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.browseengine.bobo.protobuf.BrowseRequestBPO.Selection parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.browseengine.bobo.protobuf.BrowseRequestBPO.Selection prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.browseengine.bobo.protobuf.BrowseRequestBPO.Selection result;
      
      // Construct using com.browseengine.bobo.protobuf.BrowseRequestBPO.Selection.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.browseengine.bobo.protobuf.BrowseRequestBPO.Selection();
        return builder;
      }
      
      protected com.browseengine.bobo.protobuf.BrowseRequestBPO.Selection internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.browseengine.bobo.protobuf.BrowseRequestBPO.Selection();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.browseengine.bobo.protobuf.BrowseRequestBPO.Selection.getDescriptor();
      }
      
      public com.browseengine.bobo.protobuf.BrowseRequestBPO.Selection getDefaultInstanceForType() {
        return com.browseengine.bobo.protobuf.BrowseRequestBPO.Selection.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.browseengine.bobo.protobuf.BrowseRequestBPO.Selection build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.browseengine.bobo.protobuf.BrowseRequestBPO.Selection buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.browseengine.bobo.protobuf.BrowseRequestBPO.Selection buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        if (result.values_ != java.util.Collections.EMPTY_LIST) {
          result.values_ =
            java.util.Collections.unmodifiableList(result.values_);
        }
        if (result.notValues_ != java.util.Collections.EMPTY_LIST) {
          result.notValues_ =
            java.util.Collections.unmodifiableList(result.notValues_);
        }
        if (result.props_ != java.util.Collections.EMPTY_LIST) {
          result.props_ =
            java.util.Collections.unmodifiableList(result.props_);
        }
        com.browseengine.bobo.protobuf.BrowseRequestBPO.Selection returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.browseengine.bobo.protobuf.BrowseRequestBPO.Selection) {
          return mergeFrom((com.browseengine.bobo.protobuf.BrowseRequestBPO.Selection)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.browseengine.bobo.protobuf.BrowseRequestBPO.Selection other) {
        if (other == com.browseengine.bobo.protobuf.BrowseRequestBPO.Selection.getDefaultInstance()) return this;
        if (other.hasName()) {
          setName(other.getName());
        }
        if (!other.values_.isEmpty()) {
          if (result.values_.isEmpty()) {
            result.values_ = new java.util.ArrayList<java.lang.String>();
          }
          result.values_.addAll(other.values_);
        }
        if (!other.notValues_.isEmpty()) {
          if (result.notValues_.isEmpty()) {
            result.notValues_ = new java.util.ArrayList<java.lang.String>();
          }
          result.notValues_.addAll(other.notValues_);
        }
        if (other.hasOp()) {
          setOp(other.getOp());
        }
        if (!other.props_.isEmpty()) {
          if (result.props_.isEmpty()) {
            result.props_ = new java.util.ArrayList<com.browseengine.bobo.protobuf.BrowseRequestBPO.Property>();
          }
          result.props_.addAll(other.props_);
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              setName(input.readString());
              break;
            }
            case 18: {
              addValues(input.readString());
              break;
            }
            case 26: {
              addNotValues(input.readString());
              break;
            }
            case 32: {
              int rawValue = input.readEnum();
              com.browseengine.bobo.protobuf.BrowseRequestBPO.Selection.Operation value = com.browseengine.bobo.protobuf.BrowseRequestBPO.Selection.Operation.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(4, rawValue);
              } else {
                setOp(value);
              }
              break;
            }
            case 42: {
              com.browseengine.bobo.protobuf.BrowseRequestBPO.Property.Builder subBuilder = com.browseengine.bobo.protobuf.BrowseRequestBPO.Property.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addProps(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      
      // required string name = 1;
      public boolean hasName() {
        return result.hasName();
      }
      public java.lang.String getName() {
        return result.getName();
      }
      public Builder setName(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasName = true;
        result.name_ = value;
        return this;
      }
      public Builder clearName() {
        result.hasName = false;
        result.name_ = getDefaultInstance().getName();
        return this;
      }
      
      // repeated string values = 2;
      public java.util.List<java.lang.String> getValuesList() {
        return java.util.Collections.unmodifiableList(result.values_);
      }
      public int getValuesCount() {
        return result.getValuesCount();
      }
      public java.lang.String getValues(int index) {
        return result.getValues(index);
      }
      public Builder setValues(int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.values_.set(index, value);
        return this;
      }
      public Builder addValues(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  if (result.values_.isEmpty()) {
          result.values_ = new java.util.ArrayList<java.lang.String>();
        }
        result.values_.add(value);
        return this;
      }
      public Builder addAllValues(
          java.lang.Iterable<? extends java.lang.String> values) {
        if (result.values_.isEmpty()) {
          result.values_ = new java.util.ArrayList<java.lang.String>();
        }
        super.addAll(values, result.values_);
        return this;
      }
      public Builder clearValues() {
        result.values_ = java.util.Collections.emptyList();
        return this;
      }
      
      // repeated string notValues = 3;
      public java.util.List<java.lang.String> getNotValuesList() {
        return java.util.Collections.unmodifiableList(result.notValues_);
      }
      public int getNotValuesCount() {
        return result.getNotValuesCount();
      }
      public java.lang.String getNotValues(int index) {
        return result.getNotValues(index);
      }
      public Builder setNotValues(int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.notValues_.set(index, value);
        return this;
      }
      public Builder addNotValues(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  if (result.notValues_.isEmpty()) {
          result.notValues_ = new java.util.ArrayList<java.lang.String>();
        }
        result.notValues_.add(value);
        return this;
      }
      public Builder addAllNotValues(
          java.lang.Iterable<? extends java.lang.String> values) {
        if (result.notValues_.isEmpty()) {
          result.notValues_ = new java.util.ArrayList<java.lang.String>();
        }
        super.addAll(values, result.notValues_);
        return this;
      }
      public Builder clearNotValues() {
        result.notValues_ = java.util.Collections.emptyList();
        return this;
      }
      
      // optional .com.browseengine.bobo.protobuf.Selection.Operation op = 4 [default = OR];
      public boolean hasOp() {
        return result.hasOp();
      }
      public com.browseengine.bobo.protobuf.BrowseRequestBPO.Selection.Operation getOp() {
        return result.getOp();
      }
      public Builder setOp(com.browseengine.bobo.protobuf.BrowseRequestBPO.Selection.Operation value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasOp = true;
        result.op_ = value;
        return this;
      }
      public Builder clearOp() {
        result.hasOp = false;
        result.op_ = com.browseengine.bobo.protobuf.BrowseRequestBPO.Selection.Operation.OR;
        return this;
      }
      
      // repeated .com.browseengine.bobo.protobuf.Property props = 5;
      public java.util.List<com.browseengine.bobo.protobuf.BrowseRequestBPO.Property> getPropsList() {
        return java.util.Collections.unmodifiableList(result.props_);
      }
      public int getPropsCount() {
        return result.getPropsCount();
      }
      public com.browseengine.bobo.protobuf.BrowseRequestBPO.Property getProps(int index) {
        return result.getProps(index);
      }
      public Builder setProps(int index, com.browseengine.bobo.protobuf.BrowseRequestBPO.Property value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.props_.set(index, value);
        return this;
      }
      public Builder setProps(int index, com.browseengine.bobo.protobuf.BrowseRequestBPO.Property.Builder builderForValue) {
        result.props_.set(index, builderForValue.build());
        return this;
      }
      public Builder addProps(com.browseengine.bobo.protobuf.BrowseRequestBPO.Property value) {
        if (value == null) {
          throw new NullPointerException();
        }
        if (result.props_.isEmpty()) {
          result.props_ = new java.util.ArrayList<com.browseengine.bobo.protobuf.BrowseRequestBPO.Property>();
        }
        result.props_.add(value);
        return this;
      }
      public Builder addProps(com.browseengine.bobo.protobuf.BrowseRequestBPO.Property.Builder builderForValue) {
        if (result.props_.isEmpty()) {
          result.props_ = new java.util.ArrayList<com.browseengine.bobo.protobuf.BrowseRequestBPO.Property>();
        }
        result.props_.add(builderForValue.build());
        return this;
      }
      public Builder addAllProps(
          java.lang.Iterable<? extends com.browseengine.bobo.protobuf.BrowseRequestBPO.Property> values) {
        if (result.props_.isEmpty()) {
          result.props_ = new java.util.ArrayList<com.browseengine.bobo.protobuf.BrowseRequestBPO.Property>();
        }
        super.addAll(values, result.props_);
        return this;
      }
      public Builder clearProps() {
        result.props_ = java.util.Collections.emptyList();
        return this;
      }
    }
    
    static {
      com.browseengine.bobo.protobuf.BrowseRequestBPO.getDescriptor();
    }
    
    static {
      com.browseengine.bobo.protobuf.BrowseRequestBPO.internalForceInit();
    }
  }
  
  public static final class Sort extends
      com.google.protobuf.GeneratedMessage {
    // Use Sort.newBuilder() to construct.
    private Sort() {}
    
    private static final Sort defaultInstance = new Sort();
    public static Sort getDefaultInstance() {
      return defaultInstance;
    }
    
    public Sort getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.browseengine.bobo.protobuf.BrowseRequestBPO.internal_static_com_browseengine_bobo_protobuf_Sort_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.browseengine.bobo.protobuf.BrowseRequestBPO.internal_static_com_browseengine_bobo_protobuf_Sort_fieldAccessorTable;
    }
    
    // optional string field = 1;
    public static final int FIELD_FIELD_NUMBER = 1;
    private boolean hasField;
    private java.lang.String field_ = "";
    public boolean hasField() { return hasField; }
    public java.lang.String getField() { return field_; }
    
    // optional bool reverse = 2;
    public static final int REVERSE_FIELD_NUMBER = 2;
    private boolean hasReverse;
    private boolean reverse_ = false;
    public boolean hasReverse() { return hasReverse; }
    public boolean getReverse() { return reverse_; }
    
    // optional uint32 type = 3;
    public static final int TYPE_FIELD_NUMBER = 3;
    private boolean hasType;
    private int type_ = 0;
    public boolean hasType() { return hasType; }
    public int getType() { return type_; }
    
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (hasField()) {
        output.writeString(1, getField());
      }
      if (hasReverse()) {
        output.writeBool(2, getReverse());
      }
      if (hasType()) {
        output.writeUInt32(3, getType());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasField()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getField());
      }
      if (hasReverse()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, getReverse());
      }
      if (hasType()) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, getType());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.browseengine.bobo.protobuf.BrowseRequestBPO.Sort parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.browseengine.bobo.protobuf.BrowseRequestBPO.Sort parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.browseengine.bobo.protobuf.BrowseRequestBPO.Sort parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.browseengine.bobo.protobuf.BrowseRequestBPO.Sort parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.browseengine.bobo.protobuf.BrowseRequestBPO.Sort parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.browseengine.bobo.protobuf.BrowseRequestBPO.Sort parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.browseengine.bobo.protobuf.BrowseRequestBPO.Sort parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input).buildParsed();
    }
    public static com.browseengine.bobo.protobuf.BrowseRequestBPO.Sort parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.browseengine.bobo.protobuf.BrowseRequestBPO.Sort parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.browseengine.bobo.protobuf.BrowseRequestBPO.Sort parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.browseengine.bobo.protobuf.BrowseRequestBPO.Sort prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.browseengine.bobo.protobuf.BrowseRequestBPO.Sort result;
      
      // Construct using com.browseengine.bobo.protobuf.BrowseRequestBPO.Sort.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.browseengine.bobo.protobuf.BrowseRequestBPO.Sort();
        return builder;
      }
      
      protected com.browseengine.bobo.protobuf.BrowseRequestBPO.Sort internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.browseengine.bobo.protobuf.BrowseRequestBPO.Sort();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.browseengine.bobo.protobuf.BrowseRequestBPO.Sort.getDescriptor();
      }
      
      public com.browseengine.bobo.protobuf.BrowseRequestBPO.Sort getDefaultInstanceForType() {
        return com.browseengine.bobo.protobuf.BrowseRequestBPO.Sort.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.browseengine.bobo.protobuf.BrowseRequestBPO.Sort build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.browseengine.bobo.protobuf.BrowseRequestBPO.Sort buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.browseengine.bobo.protobuf.BrowseRequestBPO.Sort buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.browseengine.bobo.protobuf.BrowseRequestBPO.Sort returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.browseengine.bobo.protobuf.BrowseRequestBPO.Sort) {
          return mergeFrom((com.browseengine.bobo.protobuf.BrowseRequestBPO.Sort)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.browseengine.bobo.protobuf.BrowseRequestBPO.Sort other) {
        if (other == com.browseengine.bobo.protobuf.BrowseRequestBPO.Sort.getDefaultInstance()) return this;
        if (other.hasField()) {
          setField(other.getField());
        }
        if (other.hasReverse()) {
          setReverse(other.getReverse());
        }
        if (other.hasType()) {
          setType(other.getType());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              setField(input.readString());
              break;
            }
            case 16: {
              setReverse(input.readBool());
              break;
            }
            case 24: {
              setType(input.readUInt32());
              break;
            }
          }
        }
      }
      
      
      // optional string field = 1;
      public boolean hasField() {
        return result.hasField();
      }
      public java.lang.String getField() {
        return result.getField();
      }
      public Builder setField(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasField = true;
        result.field_ = value;
        return this;
      }
      public Builder clearField() {
        result.hasField = false;
        result.field_ = getDefaultInstance().getField();
        return this;
      }
      
      // optional bool reverse = 2;
      public boolean hasReverse() {
        return result.hasReverse();
      }
      public boolean getReverse() {
        return result.getReverse();
      }
      public Builder setReverse(boolean value) {
        result.hasReverse = true;
        result.reverse_ = value;
        return this;
      }
      public Builder clearReverse() {
        result.hasReverse = false;
        result.reverse_ = false;
        return this;
      }
      
      // optional uint32 type = 3;
      public boolean hasType() {
        return result.hasType();
      }
      public int getType() {
        return result.getType();
      }
      public Builder setType(int value) {
        result.hasType = true;
        result.type_ = value;
        return this;
      }
      public Builder clearType() {
        result.hasType = false;
        result.type_ = 0;
        return this;
      }
    }
    
    static {
      com.browseengine.bobo.protobuf.BrowseRequestBPO.getDescriptor();
    }
    
    static {
      com.browseengine.bobo.protobuf.BrowseRequestBPO.internalForceInit();
    }
  }
  
  public static final class FacetSpec extends
      com.google.protobuf.GeneratedMessage {
    // Use FacetSpec.newBuilder() to construct.
    private FacetSpec() {}
    
    private static final FacetSpec defaultInstance = new FacetSpec();
    public static FacetSpec getDefaultInstance() {
      return defaultInstance;
    }
    
    public FacetSpec getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.browseengine.bobo.protobuf.BrowseRequestBPO.internal_static_com_browseengine_bobo_protobuf_FacetSpec_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.browseengine.bobo.protobuf.BrowseRequestBPO.internal_static_com_browseengine_bobo_protobuf_FacetSpec_fieldAccessorTable;
    }
    
    public enum SortSpec
        implements com.google.protobuf.ProtocolMessageEnum {
      ValueAsc(0, 0),
      HitsDesc(1, 1),
      ;
      
      
      public final int getNumber() { return value; }
      
      public static SortSpec valueOf(int value) {
        switch (value) {
          case 0: return ValueAsc;
          case 1: return HitsDesc;
          default: return null;
        }
      }
      
      public static com.google.protobuf.Internal.EnumLiteMap<SortSpec>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<SortSpec>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<SortSpec>() {
              public SortSpec findValueByNumber(int number) {
                return SortSpec.valueOf(number)
      ;        }
            };
      
      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.browseengine.bobo.protobuf.BrowseRequestBPO.FacetSpec.getDescriptor().getEnumTypes().get(0);
      }
      
      private static final SortSpec[] VALUES = {
        ValueAsc, HitsDesc, 
      };
      public static SortSpec valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }
      private final int index;
      private final int value;
      private SortSpec(int index, int value) {
        this.index = index;
        this.value = value;
      }
      
      static {
        com.browseengine.bobo.protobuf.BrowseRequestBPO.getDescriptor();
      }
    }
    
    // required string name = 1;
    public static final int NAME_FIELD_NUMBER = 1;
    private boolean hasName;
    private java.lang.String name_ = "";
    public boolean hasName() { return hasName; }
    public java.lang.String getName() { return name_; }
    
    // optional uint32 max = 2;
    public static final int MAX_FIELD_NUMBER = 2;
    private boolean hasMax;
    private int max_ = 0;
    public boolean hasMax() { return hasMax; }
    public int getMax() { return max_; }
    
    // optional bool expand = 3;
    public static final int EXPAND_FIELD_NUMBER = 3;
    private boolean hasExpand;
    private boolean expand_ = false;
    public boolean hasExpand() { return hasExpand; }
    public boolean getExpand() { return expand_; }
    
    // optional uint32 minCount = 4;
    public static final int MINCOUNT_FIELD_NUMBER = 4;
    private boolean hasMinCount;
    private int minCount_ = 0;
    public boolean hasMinCount() { return hasMinCount; }
    public int getMinCount() { return minCount_; }
    
    // optional .com.browseengine.bobo.protobuf.FacetSpec.SortSpec orderBy = 5 [default = HitsDesc];
    public static final int ORDERBY_FIELD_NUMBER = 5;
    private boolean hasOrderBy;
    private com.browseengine.bobo.protobuf.BrowseRequestBPO.FacetSpec.SortSpec orderBy_ = com.browseengine.bobo.protobuf.BrowseRequestBPO.FacetSpec.SortSpec.HitsDesc;
    public boolean hasOrderBy() { return hasOrderBy; }
    public com.browseengine.bobo.protobuf.BrowseRequestBPO.FacetSpec.SortSpec getOrderBy() { return orderBy_; }
    
    public final boolean isInitialized() {
      if (!hasName) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (hasName()) {
        output.writeString(1, getName());
      }
      if (hasMax()) {
        output.writeUInt32(2, getMax());
      }
      if (hasExpand()) {
        output.writeBool(3, getExpand());
      }
      if (hasMinCount()) {
        output.writeUInt32(4, getMinCount());
      }
      if (hasOrderBy()) {
        output.writeEnum(5, getOrderBy().getNumber());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasName()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getName());
      }
      if (hasMax()) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, getMax());
      }
      if (hasExpand()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, getExpand());
      }
      if (hasMinCount()) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(4, getMinCount());
      }
      if (hasOrderBy()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(5, getOrderBy().getNumber());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.browseengine.bobo.protobuf.BrowseRequestBPO.FacetSpec parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.browseengine.bobo.protobuf.BrowseRequestBPO.FacetSpec parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.browseengine.bobo.protobuf.BrowseRequestBPO.FacetSpec parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.browseengine.bobo.protobuf.BrowseRequestBPO.FacetSpec parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.browseengine.bobo.protobuf.BrowseRequestBPO.FacetSpec parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.browseengine.bobo.protobuf.BrowseRequestBPO.FacetSpec parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.browseengine.bobo.protobuf.BrowseRequestBPO.FacetSpec parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input).buildParsed();
    }
    public static com.browseengine.bobo.protobuf.BrowseRequestBPO.FacetSpec parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.browseengine.bobo.protobuf.BrowseRequestBPO.FacetSpec parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.browseengine.bobo.protobuf.BrowseRequestBPO.FacetSpec parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.browseengine.bobo.protobuf.BrowseRequestBPO.FacetSpec prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.browseengine.bobo.protobuf.BrowseRequestBPO.FacetSpec result;
      
      // Construct using com.browseengine.bobo.protobuf.BrowseRequestBPO.FacetSpec.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.browseengine.bobo.protobuf.BrowseRequestBPO.FacetSpec();
        return builder;
      }
      
      protected com.browseengine.bobo.protobuf.BrowseRequestBPO.FacetSpec internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.browseengine.bobo.protobuf.BrowseRequestBPO.FacetSpec();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.browseengine.bobo.protobuf.BrowseRequestBPO.FacetSpec.getDescriptor();
      }
      
      public com.browseengine.bobo.protobuf.BrowseRequestBPO.FacetSpec getDefaultInstanceForType() {
        return com.browseengine.bobo.protobuf.BrowseRequestBPO.FacetSpec.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.browseengine.bobo.protobuf.BrowseRequestBPO.FacetSpec build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.browseengine.bobo.protobuf.BrowseRequestBPO.FacetSpec buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.browseengine.bobo.protobuf.BrowseRequestBPO.FacetSpec buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.browseengine.bobo.protobuf.BrowseRequestBPO.FacetSpec returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.browseengine.bobo.protobuf.BrowseRequestBPO.FacetSpec) {
          return mergeFrom((com.browseengine.bobo.protobuf.BrowseRequestBPO.FacetSpec)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.browseengine.bobo.protobuf.BrowseRequestBPO.FacetSpec other) {
        if (other == com.browseengine.bobo.protobuf.BrowseRequestBPO.FacetSpec.getDefaultInstance()) return this;
        if (other.hasName()) {
          setName(other.getName());
        }
        if (other.hasMax()) {
          setMax(other.getMax());
        }
        if (other.hasExpand()) {
          setExpand(other.getExpand());
        }
        if (other.hasMinCount()) {
          setMinCount(other.getMinCount());
        }
        if (other.hasOrderBy()) {
          setOrderBy(other.getOrderBy());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              setName(input.readString());
              break;
            }
            case 16: {
              setMax(input.readUInt32());
              break;
            }
            case 24: {
              setExpand(input.readBool());
              break;
            }
            case 32: {
              setMinCount(input.readUInt32());
              break;
            }
            case 40: {
              int rawValue = input.readEnum();
              com.browseengine.bobo.protobuf.BrowseRequestBPO.FacetSpec.SortSpec value = com.browseengine.bobo.protobuf.BrowseRequestBPO.FacetSpec.SortSpec.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(5, rawValue);
              } else {
                setOrderBy(value);
              }
              break;
            }
          }
        }
      }
      
      
      // required string name = 1;
      public boolean hasName() {
        return result.hasName();
      }
      public java.lang.String getName() {
        return result.getName();
      }
      public Builder setName(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasName = true;
        result.name_ = value;
        return this;
      }
      public Builder clearName() {
        result.hasName = false;
        result.name_ = getDefaultInstance().getName();
        return this;
      }
      
      // optional uint32 max = 2;
      public boolean hasMax() {
        return result.hasMax();
      }
      public int getMax() {
        return result.getMax();
      }
      public Builder setMax(int value) {
        result.hasMax = true;
        result.max_ = value;
        return this;
      }
      public Builder clearMax() {
        result.hasMax = false;
        result.max_ = 0;
        return this;
      }
      
      // optional bool expand = 3;
      public boolean hasExpand() {
        return result.hasExpand();
      }
      public boolean getExpand() {
        return result.getExpand();
      }
      public Builder setExpand(boolean value) {
        result.hasExpand = true;
        result.expand_ = value;
        return this;
      }
      public Builder clearExpand() {
        result.hasExpand = false;
        result.expand_ = false;
        return this;
      }
      
      // optional uint32 minCount = 4;
      public boolean hasMinCount() {
        return result.hasMinCount();
      }
      public int getMinCount() {
        return result.getMinCount();
      }
      public Builder setMinCount(int value) {
        result.hasMinCount = true;
        result.minCount_ = value;
        return this;
      }
      public Builder clearMinCount() {
        result.hasMinCount = false;
        result.minCount_ = 0;
        return this;
      }
      
      // optional .com.browseengine.bobo.protobuf.FacetSpec.SortSpec orderBy = 5 [default = HitsDesc];
      public boolean hasOrderBy() {
        return result.hasOrderBy();
      }
      public com.browseengine.bobo.protobuf.BrowseRequestBPO.FacetSpec.SortSpec getOrderBy() {
        return result.getOrderBy();
      }
      public Builder setOrderBy(com.browseengine.bobo.protobuf.BrowseRequestBPO.FacetSpec.SortSpec value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasOrderBy = true;
        result.orderBy_ = value;
        return this;
      }
      public Builder clearOrderBy() {
        result.hasOrderBy = false;
        result.orderBy_ = com.browseengine.bobo.protobuf.BrowseRequestBPO.FacetSpec.SortSpec.HitsDesc;
        return this;
      }
    }
    
    static {
      com.browseengine.bobo.protobuf.BrowseRequestBPO.getDescriptor();
    }
    
    static {
      com.browseengine.bobo.protobuf.BrowseRequestBPO.internalForceInit();
    }
  }
  
  public static final class Request extends
      com.google.protobuf.GeneratedMessage {
    // Use Request.newBuilder() to construct.
    private Request() {}
    
    private static final Request defaultInstance = new Request();
    public static Request getDefaultInstance() {
      return defaultInstance;
    }
    
    public Request getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.browseengine.bobo.protobuf.BrowseRequestBPO.internal_static_com_browseengine_bobo_protobuf_Request_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.browseengine.bobo.protobuf.BrowseRequestBPO.internal_static_com_browseengine_bobo_protobuf_Request_fieldAccessorTable;
    }
    
    // repeated .com.browseengine.bobo.protobuf.Selection selections = 1;
    public static final int SELECTIONS_FIELD_NUMBER = 1;
    private java.util.List<com.browseengine.bobo.protobuf.BrowseRequestBPO.Selection> selections_ =
      java.util.Collections.emptyList();
    public java.util.List<com.browseengine.bobo.protobuf.BrowseRequestBPO.Selection> getSelectionsList() {
      return selections_;
    }
    public int getSelectionsCount() { return selections_.size(); }
    public com.browseengine.bobo.protobuf.BrowseRequestBPO.Selection getSelections(int index) {
      return selections_.get(index);
    }
    
    // optional uint32 offset = 2;
    public static final int OFFSET_FIELD_NUMBER = 2;
    private boolean hasOffset;
    private int offset_ = 0;
    public boolean hasOffset() { return hasOffset; }
    public int getOffset() { return offset_; }
    
    // optional uint32 count = 3;
    public static final int COUNT_FIELD_NUMBER = 3;
    private boolean hasCount;
    private int count_ = 0;
    public boolean hasCount() { return hasCount; }
    public int getCount() { return count_; }
    
    // repeated .com.browseengine.bobo.protobuf.Sort sort = 4;
    public static final int SORT_FIELD_NUMBER = 4;
    private java.util.List<com.browseengine.bobo.protobuf.BrowseRequestBPO.Sort> sort_ =
      java.util.Collections.emptyList();
    public java.util.List<com.browseengine.bobo.protobuf.BrowseRequestBPO.Sort> getSortList() {
      return sort_;
    }
    public int getSortCount() { return sort_.size(); }
    public com.browseengine.bobo.protobuf.BrowseRequestBPO.Sort getSort(int index) {
      return sort_.get(index);
    }
    
    // repeated .com.browseengine.bobo.protobuf.FacetSpec facetSpecs = 5;
    public static final int FACETSPECS_FIELD_NUMBER = 5;
    private java.util.List<com.browseengine.bobo.protobuf.BrowseRequestBPO.FacetSpec> facetSpecs_ =
      java.util.Collections.emptyList();
    public java.util.List<com.browseengine.bobo.protobuf.BrowseRequestBPO.FacetSpec> getFacetSpecsList() {
      return facetSpecs_;
    }
    public int getFacetSpecsCount() { return facetSpecs_.size(); }
    public com.browseengine.bobo.protobuf.BrowseRequestBPO.FacetSpec getFacetSpecs(int index) {
      return facetSpecs_.get(index);
    }
    
    // optional string query = 6;
    public static final int QUERY_FIELD_NUMBER = 6;
    private boolean hasQuery;
    private java.lang.String query_ = "";
    public boolean hasQuery() { return hasQuery; }
    public java.lang.String getQuery() { return query_; }
    
    public final boolean isInitialized() {
      for (com.browseengine.bobo.protobuf.BrowseRequestBPO.Selection element : getSelectionsList()) {
        if (!element.isInitialized()) return false;
      }
      for (com.browseengine.bobo.protobuf.BrowseRequestBPO.FacetSpec element : getFacetSpecsList()) {
        if (!element.isInitialized()) return false;
      }
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (com.browseengine.bobo.protobuf.BrowseRequestBPO.Selection element : getSelectionsList()) {
        output.writeMessage(1, element);
      }
      if (hasOffset()) {
        output.writeUInt32(2, getOffset());
      }
      if (hasCount()) {
        output.writeUInt32(3, getCount());
      }
      for (com.browseengine.bobo.protobuf.BrowseRequestBPO.Sort element : getSortList()) {
        output.writeMessage(4, element);
      }
      for (com.browseengine.bobo.protobuf.BrowseRequestBPO.FacetSpec element : getFacetSpecsList()) {
        output.writeMessage(5, element);
      }
      if (hasQuery()) {
        output.writeString(6, getQuery());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      for (com.browseengine.bobo.protobuf.BrowseRequestBPO.Selection element : getSelectionsList()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, element);
      }
      if (hasOffset()) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, getOffset());
      }
      if (hasCount()) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, getCount());
      }
      for (com.browseengine.bobo.protobuf.BrowseRequestBPO.Sort element : getSortList()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, element);
      }
      for (com.browseengine.bobo.protobuf.BrowseRequestBPO.FacetSpec element : getFacetSpecsList()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, element);
      }
      if (hasQuery()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(6, getQuery());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.browseengine.bobo.protobuf.BrowseRequestBPO.Request parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.browseengine.bobo.protobuf.BrowseRequestBPO.Request parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.browseengine.bobo.protobuf.BrowseRequestBPO.Request parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.browseengine.bobo.protobuf.BrowseRequestBPO.Request parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.browseengine.bobo.protobuf.BrowseRequestBPO.Request parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.browseengine.bobo.protobuf.BrowseRequestBPO.Request parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.browseengine.bobo.protobuf.BrowseRequestBPO.Request parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input).buildParsed();
    }
    public static com.browseengine.bobo.protobuf.BrowseRequestBPO.Request parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.browseengine.bobo.protobuf.BrowseRequestBPO.Request parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.browseengine.bobo.protobuf.BrowseRequestBPO.Request parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.browseengine.bobo.protobuf.BrowseRequestBPO.Request prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.browseengine.bobo.protobuf.BrowseRequestBPO.Request result;
      
      // Construct using com.browseengine.bobo.protobuf.BrowseRequestBPO.Request.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.browseengine.bobo.protobuf.BrowseRequestBPO.Request();
        return builder;
      }
      
      protected com.browseengine.bobo.protobuf.BrowseRequestBPO.Request internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.browseengine.bobo.protobuf.BrowseRequestBPO.Request();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.browseengine.bobo.protobuf.BrowseRequestBPO.Request.getDescriptor();
      }
      
      public com.browseengine.bobo.protobuf.BrowseRequestBPO.Request getDefaultInstanceForType() {
        return com.browseengine.bobo.protobuf.BrowseRequestBPO.Request.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.browseengine.bobo.protobuf.BrowseRequestBPO.Request build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.browseengine.bobo.protobuf.BrowseRequestBPO.Request buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.browseengine.bobo.protobuf.BrowseRequestBPO.Request buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        if (result.selections_ != java.util.Collections.EMPTY_LIST) {
          result.selections_ =
            java.util.Collections.unmodifiableList(result.selections_);
        }
        if (result.sort_ != java.util.Collections.EMPTY_LIST) {
          result.sort_ =
            java.util.Collections.unmodifiableList(result.sort_);
        }
        if (result.facetSpecs_ != java.util.Collections.EMPTY_LIST) {
          result.facetSpecs_ =
            java.util.Collections.unmodifiableList(result.facetSpecs_);
        }
        com.browseengine.bobo.protobuf.BrowseRequestBPO.Request returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.browseengine.bobo.protobuf.BrowseRequestBPO.Request) {
          return mergeFrom((com.browseengine.bobo.protobuf.BrowseRequestBPO.Request)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.browseengine.bobo.protobuf.BrowseRequestBPO.Request other) {
        if (other == com.browseengine.bobo.protobuf.BrowseRequestBPO.Request.getDefaultInstance()) return this;
        if (!other.selections_.isEmpty()) {
          if (result.selections_.isEmpty()) {
            result.selections_ = new java.util.ArrayList<com.browseengine.bobo.protobuf.BrowseRequestBPO.Selection>();
          }
          result.selections_.addAll(other.selections_);
        }
        if (other.hasOffset()) {
          setOffset(other.getOffset());
        }
        if (other.hasCount()) {
          setCount(other.getCount());
        }
        if (!other.sort_.isEmpty()) {
          if (result.sort_.isEmpty()) {
            result.sort_ = new java.util.ArrayList<com.browseengine.bobo.protobuf.BrowseRequestBPO.Sort>();
          }
          result.sort_.addAll(other.sort_);
        }
        if (!other.facetSpecs_.isEmpty()) {
          if (result.facetSpecs_.isEmpty()) {
            result.facetSpecs_ = new java.util.ArrayList<com.browseengine.bobo.protobuf.BrowseRequestBPO.FacetSpec>();
          }
          result.facetSpecs_.addAll(other.facetSpecs_);
        }
        if (other.hasQuery()) {
          setQuery(other.getQuery());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              com.browseengine.bobo.protobuf.BrowseRequestBPO.Selection.Builder subBuilder = com.browseengine.bobo.protobuf.BrowseRequestBPO.Selection.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addSelections(subBuilder.buildPartial());
              break;
            }
            case 16: {
              setOffset(input.readUInt32());
              break;
            }
            case 24: {
              setCount(input.readUInt32());
              break;
            }
            case 34: {
              com.browseengine.bobo.protobuf.BrowseRequestBPO.Sort.Builder subBuilder = com.browseengine.bobo.protobuf.BrowseRequestBPO.Sort.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addSort(subBuilder.buildPartial());
              break;
            }
            case 42: {
              com.browseengine.bobo.protobuf.BrowseRequestBPO.FacetSpec.Builder subBuilder = com.browseengine.bobo.protobuf.BrowseRequestBPO.FacetSpec.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addFacetSpecs(subBuilder.buildPartial());
              break;
            }
            case 50: {
              setQuery(input.readString());
              break;
            }
          }
        }
      }
      
      
      // repeated .com.browseengine.bobo.protobuf.Selection selections = 1;
      public java.util.List<com.browseengine.bobo.protobuf.BrowseRequestBPO.Selection> getSelectionsList() {
        return java.util.Collections.unmodifiableList(result.selections_);
      }
      public int getSelectionsCount() {
        return result.getSelectionsCount();
      }
      public com.browseengine.bobo.protobuf.BrowseRequestBPO.Selection getSelections(int index) {
        return result.getSelections(index);
      }
      public Builder setSelections(int index, com.browseengine.bobo.protobuf.BrowseRequestBPO.Selection value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.selections_.set(index, value);
        return this;
      }
      public Builder setSelections(int index, com.browseengine.bobo.protobuf.BrowseRequestBPO.Selection.Builder builderForValue) {
        result.selections_.set(index, builderForValue.build());
        return this;
      }
      public Builder addSelections(com.browseengine.bobo.protobuf.BrowseRequestBPO.Selection value) {
        if (value == null) {
          throw new NullPointerException();
        }
        if (result.selections_.isEmpty()) {
          result.selections_ = new java.util.ArrayList<com.browseengine.bobo.protobuf.BrowseRequestBPO.Selection>();
        }
        result.selections_.add(value);
        return this;
      }
      public Builder addSelections(com.browseengine.bobo.protobuf.BrowseRequestBPO.Selection.Builder builderForValue) {
        if (result.selections_.isEmpty()) {
          result.selections_ = new java.util.ArrayList<com.browseengine.bobo.protobuf.BrowseRequestBPO.Selection>();
        }
        result.selections_.add(builderForValue.build());
        return this;
      }
      public Builder addAllSelections(
          java.lang.Iterable<? extends com.browseengine.bobo.protobuf.BrowseRequestBPO.Selection> values) {
        if (result.selections_.isEmpty()) {
          result.selections_ = new java.util.ArrayList<com.browseengine.bobo.protobuf.BrowseRequestBPO.Selection>();
        }
        super.addAll(values, result.selections_);
        return this;
      }
      public Builder clearSelections() {
        result.selections_ = java.util.Collections.emptyList();
        return this;
      }
      
      // optional uint32 offset = 2;
      public boolean hasOffset() {
        return result.hasOffset();
      }
      public int getOffset() {
        return result.getOffset();
      }
      public Builder setOffset(int value) {
        result.hasOffset = true;
        result.offset_ = value;
        return this;
      }
      public Builder clearOffset() {
        result.hasOffset = false;
        result.offset_ = 0;
        return this;
      }
      
      // optional uint32 count = 3;
      public boolean hasCount() {
        return result.hasCount();
      }
      public int getCount() {
        return result.getCount();
      }
      public Builder setCount(int value) {
        result.hasCount = true;
        result.count_ = value;
        return this;
      }
      public Builder clearCount() {
        result.hasCount = false;
        result.count_ = 0;
        return this;
      }
      
      // repeated .com.browseengine.bobo.protobuf.Sort sort = 4;
      public java.util.List<com.browseengine.bobo.protobuf.BrowseRequestBPO.Sort> getSortList() {
        return java.util.Collections.unmodifiableList(result.sort_);
      }
      public int getSortCount() {
        return result.getSortCount();
      }
      public com.browseengine.bobo.protobuf.BrowseRequestBPO.Sort getSort(int index) {
        return result.getSort(index);
      }
      public Builder setSort(int index, com.browseengine.bobo.protobuf.BrowseRequestBPO.Sort value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.sort_.set(index, value);
        return this;
      }
      public Builder setSort(int index, com.browseengine.bobo.protobuf.BrowseRequestBPO.Sort.Builder builderForValue) {
        result.sort_.set(index, builderForValue.build());
        return this;
      }
      public Builder addSort(com.browseengine.bobo.protobuf.BrowseRequestBPO.Sort value) {
        if (value == null) {
          throw new NullPointerException();
        }
        if (result.sort_.isEmpty()) {
          result.sort_ = new java.util.ArrayList<com.browseengine.bobo.protobuf.BrowseRequestBPO.Sort>();
        }
        result.sort_.add(value);
        return this;
      }
      public Builder addSort(com.browseengine.bobo.protobuf.BrowseRequestBPO.Sort.Builder builderForValue) {
        if (result.sort_.isEmpty()) {
          result.sort_ = new java.util.ArrayList<com.browseengine.bobo.protobuf.BrowseRequestBPO.Sort>();
        }
        result.sort_.add(builderForValue.build());
        return this;
      }
      public Builder addAllSort(
          java.lang.Iterable<? extends com.browseengine.bobo.protobuf.BrowseRequestBPO.Sort> values) {
        if (result.sort_.isEmpty()) {
          result.sort_ = new java.util.ArrayList<com.browseengine.bobo.protobuf.BrowseRequestBPO.Sort>();
        }
        super.addAll(values, result.sort_);
        return this;
      }
      public Builder clearSort() {
        result.sort_ = java.util.Collections.emptyList();
        return this;
      }
      
      // repeated .com.browseengine.bobo.protobuf.FacetSpec facetSpecs = 5;
      public java.util.List<com.browseengine.bobo.protobuf.BrowseRequestBPO.FacetSpec> getFacetSpecsList() {
        return java.util.Collections.unmodifiableList(result.facetSpecs_);
      }
      public int getFacetSpecsCount() {
        return result.getFacetSpecsCount();
      }
      public com.browseengine.bobo.protobuf.BrowseRequestBPO.FacetSpec getFacetSpecs(int index) {
        return result.getFacetSpecs(index);
      }
      public Builder setFacetSpecs(int index, com.browseengine.bobo.protobuf.BrowseRequestBPO.FacetSpec value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.facetSpecs_.set(index, value);
        return this;
      }
      public Builder setFacetSpecs(int index, com.browseengine.bobo.protobuf.BrowseRequestBPO.FacetSpec.Builder builderForValue) {
        result.facetSpecs_.set(index, builderForValue.build());
        return this;
      }
      public Builder addFacetSpecs(com.browseengine.bobo.protobuf.BrowseRequestBPO.FacetSpec value) {
        if (value == null) {
          throw new NullPointerException();
        }
        if (result.facetSpecs_.isEmpty()) {
          result.facetSpecs_ = new java.util.ArrayList<com.browseengine.bobo.protobuf.BrowseRequestBPO.FacetSpec>();
        }
        result.facetSpecs_.add(value);
        return this;
      }
      public Builder addFacetSpecs(com.browseengine.bobo.protobuf.BrowseRequestBPO.FacetSpec.Builder builderForValue) {
        if (result.facetSpecs_.isEmpty()) {
          result.facetSpecs_ = new java.util.ArrayList<com.browseengine.bobo.protobuf.BrowseRequestBPO.FacetSpec>();
        }
        result.facetSpecs_.add(builderForValue.build());
        return this;
      }
      public Builder addAllFacetSpecs(
          java.lang.Iterable<? extends com.browseengine.bobo.protobuf.BrowseRequestBPO.FacetSpec> values) {
        if (result.facetSpecs_.isEmpty()) {
          result.facetSpecs_ = new java.util.ArrayList<com.browseengine.bobo.protobuf.BrowseRequestBPO.FacetSpec>();
        }
        super.addAll(values, result.facetSpecs_);
        return this;
      }
      public Builder clearFacetSpecs() {
        result.facetSpecs_ = java.util.Collections.emptyList();
        return this;
      }
      
      // optional string query = 6;
      public boolean hasQuery() {
        return result.hasQuery();
      }
      public java.lang.String getQuery() {
        return result.getQuery();
      }
      public Builder setQuery(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasQuery = true;
        result.query_ = value;
        return this;
      }
      public Builder clearQuery() {
        result.hasQuery = false;
        result.query_ = getDefaultInstance().getQuery();
        return this;
      }
    }
    
    static {
      com.browseengine.bobo.protobuf.BrowseRequestBPO.getDescriptor();
    }
    
    static {
      com.browseengine.bobo.protobuf.BrowseRequestBPO.internalForceInit();
    }
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_browseengine_bobo_protobuf_Property_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_browseengine_bobo_protobuf_Property_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_browseengine_bobo_protobuf_Selection_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_browseengine_bobo_protobuf_Selection_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_browseengine_bobo_protobuf_Sort_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_browseengine_bobo_protobuf_Sort_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_browseengine_bobo_protobuf_FacetSpec_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_browseengine_bobo_protobuf_FacetSpec_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_browseengine_bobo_protobuf_Request_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_browseengine_bobo_protobuf_Request_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017browseReq.proto\022\036com.browseengine.bobo" +
      ".protobuf\"$\n\010Property\022\013\n\003key\030\001 \002(\t\022\013\n\003va" +
      "l\030\002 \001(\t\"\330\001\n\tSelection\022\014\n\004name\030\001 \002(\t\022\016\n\006v" +
      "alues\030\002 \003(\t\022\021\n\tnotValues\030\003 \003(\t\022C\n\002op\030\004 \001" +
      "(\01623.com.browseengine.bobo.protobuf.Sele" +
      "ction.Operation:\002OR\0227\n\005props\030\005 \003(\0132(.com" +
      ".browseengine.bobo.protobuf.Property\"\034\n\t" +
      "Operation\022\006\n\002OR\020\000\022\007\n\003AND\020\001\"4\n\004Sort\022\r\n\005fi" +
      "eld\030\001 \001(\t\022\017\n\007reverse\030\002 \001(\010\022\014\n\004type\030\003 \001(\r" +
      "\"\277\001\n\tFacetSpec\022\014\n\004name\030\001 \002(\t\022\013\n\003max\030\002 \001(",
      "\r\022\016\n\006expand\030\003 \001(\010\022\020\n\010minCount\030\004 \001(\r\022M\n\007o" +
      "rderBy\030\005 \001(\01622.com.browseengine.bobo.pro" +
      "tobuf.FacetSpec.SortSpec:\010HitsDesc\"&\n\010So" +
      "rtSpec\022\014\n\010ValueAsc\020\000\022\014\n\010HitsDesc\020\001\"\351\001\n\007R" +
      "equest\022=\n\nselections\030\001 \003(\0132).com.browsee" +
      "ngine.bobo.protobuf.Selection\022\016\n\006offset\030" +
      "\002 \001(\r\022\r\n\005count\030\003 \001(\r\0222\n\004sort\030\004 \003(\0132$.com" +
      ".browseengine.bobo.protobuf.Sort\022=\n\nface" +
      "tSpecs\030\005 \003(\0132).com.browseengine.bobo.pro" +
      "tobuf.FacetSpec\022\r\n\005query\030\006 \001(\tB4\n\036com.br",
      "owseengine.bobo.protobufB\020BrowseRequestB" +
      "POH\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_browseengine_bobo_protobuf_Property_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_browseengine_bobo_protobuf_Property_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_browseengine_bobo_protobuf_Property_descriptor,
              new java.lang.String[] { "Key", "Val", },
              com.browseengine.bobo.protobuf.BrowseRequestBPO.Property.class,
              com.browseengine.bobo.protobuf.BrowseRequestBPO.Property.Builder.class);
          internal_static_com_browseengine_bobo_protobuf_Selection_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_browseengine_bobo_protobuf_Selection_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_browseengine_bobo_protobuf_Selection_descriptor,
              new java.lang.String[] { "Name", "Values", "NotValues", "Op", "Props", },
              com.browseengine.bobo.protobuf.BrowseRequestBPO.Selection.class,
              com.browseengine.bobo.protobuf.BrowseRequestBPO.Selection.Builder.class);
          internal_static_com_browseengine_bobo_protobuf_Sort_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_com_browseengine_bobo_protobuf_Sort_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_browseengine_bobo_protobuf_Sort_descriptor,
              new java.lang.String[] { "Field", "Reverse", "Type", },
              com.browseengine.bobo.protobuf.BrowseRequestBPO.Sort.class,
              com.browseengine.bobo.protobuf.BrowseRequestBPO.Sort.Builder.class);
          internal_static_com_browseengine_bobo_protobuf_FacetSpec_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_com_browseengine_bobo_protobuf_FacetSpec_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_browseengine_bobo_protobuf_FacetSpec_descriptor,
              new java.lang.String[] { "Name", "Max", "Expand", "MinCount", "OrderBy", },
              com.browseengine.bobo.protobuf.BrowseRequestBPO.FacetSpec.class,
              com.browseengine.bobo.protobuf.BrowseRequestBPO.FacetSpec.Builder.class);
          internal_static_com_browseengine_bobo_protobuf_Request_descriptor =
            getDescriptor().getMessageTypes().get(4);
          internal_static_com_browseengine_bobo_protobuf_Request_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_browseengine_bobo_protobuf_Request_descriptor,
              new java.lang.String[] { "Selections", "Offset", "Count", "Sort", "FacetSpecs", "Query", },
              com.browseengine.bobo.protobuf.BrowseRequestBPO.Request.class,
              com.browseengine.bobo.protobuf.BrowseRequestBPO.Request.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  public static void internalForceInit() {}
}
